### ISSUE TITLE
Potential to make work for other loci

### ISSUE THREAD

**Issue by JamieHeather** [williamdlees/receptor_utils#1]
Hi William, great repo with a lot of potential. 

It would be wonderful to expand it to other loci (especially the **best** loci, TCRs) to have a unified tool. After having a quick look, it looks like you can get part of the way there fairly quickly, e.g. maybe by:

1) Tweak `extract_refs` to take a 'locus' argument, e.g. something like:

````python
def main():
    parser = argparse.ArgumentParser(description='Extract reference files for nominated species')
    parser.add_argument('imgt_file', help='gapped imgt reference file')
    parser.add_argument('species_name', help='species name for IMGT file in quotes, e.g. "Homo sapiens", "Macaca mulatta"')
    parser.add_argument('-L', '--locus', help='locus identifier, e.g. "IGH" (default), "IGK", "TRB", "TRG"',
                        default='IGH', required=False)
    parser.add_argument('-F', '--functional_only', action='store_true')
    args = parser.parse_args()

    segs = {'IGH': ['IGHV', 'IGHD', 'IGHJ', 'CH'],
            'IGK': ['IGKV', 'IGKJ', 'IGKC'],
            'IGL': ['IGLV', 'IGLJ', 'IGLC'],
            'TRA': ['TRAV', 'TRAJ', 'TRAC'],
            'TRB': ['TRBV', 'TRBD', 'TRBJ', 'TRBC'],
            'TRG': ['TRGV', 'TRGJ', 'TRGC'],
            'TRD': ['TRDV', 'TRDD', 'TRDJ', 'TRDC']}

    refs = simple.read_imgt_fasta(args.imgt_file, [args.species_name], segs[args.locus],
                                  functional_only=args.functional_only)

    simple.write_fasta(refs[args.species_name][args.locus + 'V'],
                       '%s_IGHV_gapped.fasta'.replace('IGHV', args.locus + 'V') %args.species_name.replace(' ', '_'))

    ungapped = {}

    for seg in segs[args.locus]:
        ungapped[seg] = {}
        for id, seq in refs[args.species_name][seg].items():
            ungapped[seg][id] = seq.replace('.', '')

        simple.write_fasta(ungapped[seg], '%s_%s.fasta' % (args.species_name.replace(' ', '_'), seg))
````

2) Updating `simple_bio_seq` to take that extra info, e.g. something like:

````python
def read_imgt_fasta(infile, species, chains=('IGHV', 'IGHD', 'IGHJ', 'CH'), functional_only=False):
    res = {}
    for sp in species:
        res[sp] = {}
        for chain in chains:
            res[sp][chain] = {}

    recs = SeqIO.parse(infile, 'fasta')

    for rec in recs:
        for sp in species:
            for chain in chains:
                if ('-REGION' in rec.description or chain == 'CH' or 'EX' in rec.description) \
                        and sp in rec.description and chain in rec.description:
                    if not functional_only or '|F|' in rec.description:
                        if 'V' not in chain or len(rec.seq) > 280:       # strip out obviously incomplete Vs
                            name = rec.description.split('|')[1]
                            type = rec.description.split('|')[4]

                            if chain == 'CH' or ('EX' in rec.description and chain in rec.description):
                                gene, allele = name.split('*')
                                res[sp][chain][gene + '_' + type + '*' + allele] = str(rec.seq).upper()
                            else:
                                res[sp][chain][name] = str(rec.seq).upper()
````

It's not quite perfect, as TCR constant regions are labelled very differently to IGH) and seem to fall out when `read_imgt_fasta` is called from `extract_refs`, but it gets the bulk of the data in, as a starting point.

**Comment by williamdlees** [comment]
Thanks Jamie. Shows how focussed on IGH I have been! Have included your fixes in a new release and they seem to work well. I see TR constant regions coming over which seem to match those in the reference file, but perhaps some a missing. Lots to do on the constant region anyway...

**Comment by williamdlees** [comment]
Thanks Jamie, yes that really ought to be done, will work it in.

 

From: Jamie Heather ***@***.***> 
Sent: 07 August 2022 22:34
To: williamdlees/receptor_utils ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [williamdlees/receptor_utils] Potential to make work for other loci (Issue #1)

 

Hi William, great repo with a lot of potential.

It would be wonderful to expand it to other loci (especially the best loci, TCRs) to have a unified tool. After having a quick look, it looks like you can get part of the way there fairly quickly, e.g. maybe by:

1.	Tweak extract_refs to take a 'locus' argument, e.g. something like:

def main():
    parser = argparse.ArgumentParser(description='Extract reference files for nominated species')
    parser.add_argument('imgt_file', help='gapped imgt reference file')
    parser.add_argument('species_name', help='species name for IMGT file in quotes, e.g. "Homo sapiens", "Macaca mulatta"')
    parser.add_argument('-L', '--locus', help='locus identifier, e.g. "IGH" (default), "IGK", "TRB", "TRG"',
                        default='IGH', required=False)
    parser.add_argument('-F', '--functional_only', action='store_true')
    args = parser.parse_args()
 
    segs = {'IGH': ['IGHV', 'IGHD', 'IGHJ', 'CH'],
            'IGK': ['IGKV', 'IGKJ', 'IGKC'],
            'IGL': ['IGLV', 'IGLJ', 'IGLC'],
            'TRA': ['TRAV', 'TRAJ', 'TRAC'],
            'TRB': ['TRBV', 'TRBD', 'TRBJ', 'TRBC'],
            'TRG': ['TRGV', 'TRGJ', 'TRGC'],
            'TRD': ['TRDV', 'TRDD', 'TRDJ', 'TRDC']}
 
    refs = simple.read_imgt_fasta(args.imgt_file, [args.species_name], segs[args.locus],
                                  functional_only=args.functional_only)
 
    simple.write_fasta(refs[args.species_name][args.locus + 'V'],
                       '%s_IGHV_gapped.fasta'.replace('IGHV', args.locus + 'V') %args.species_name.replace(' ', '_'))
 
    ungapped = {}
 
    for seg in segs[args.locus]:
        ungapped[seg] = {}
        for id, seq in refs[args.species_name][seg].items():
            ungapped[seg][id] = seq.replace('.', '')
 
        simple.write_fasta(ungapped[seg], '%s_%s.fasta' % (args.species_name.replace(' ', '_'), seg))

2.	Updating simple_bio_seq to take that extra info, e.g. something like:

def read_imgt_fasta(infile, species, chains=('IGHV', 'IGHD', 'IGHJ', 'CH'), functional_only=False):
    res = {}
    for sp in species:
        res[sp] = {}
        for chain in chains:
            res[sp][chain] = {}
 
    recs = SeqIO.parse(infile, 'fasta')
 
    for rec in recs:
        for sp in species:
            for chain in chains:
                if ('-REGION' in rec.description or chain == 'CH' or 'EX' in rec.description) \
                        and sp in rec.description and chain in rec.description:
                    if not functional_only or '|F|' in rec.description:
                        if 'V' not in chain or len(rec.seq) > 280:       # strip out obviously incomplete Vs
                            name = rec.description.split('|')[1]
                            type = rec.description.split('|')[4]
 
                            if chain == 'CH' or ('EX' in rec.description and chain in rec.description):
                                gene, allele = name.split('*')
                                res[sp][chain][gene + '_' + type + '*' + allele] = str(rec.seq).upper()
                            else:
                                res[sp][chain][name] = str(rec.seq).upper()

It's not quite perfect, as TCR constant regions are labelled very differently to IGH) and seem to fall out when read_imgt_fasta is called from extract_refs, but it gets the bulk of the data in, as a starting point.
